In [22]:
from sympy import symbols, Eq, linear_eq_to_matrix, Matrix

def montar_sistema(equacoes):
    n = len(equacoes)
    variaveis = symbols(f'x1:{n+1}')
    eqs = []
    for eq in equacoes:
        lhs, rhs = eq.split('=')
        eqs.append(Eq(eval(lhs, dict(zip([str(v) for v in variaveis], variaveis))), eval(rhs)))
    A, b = linear_eq_to_matrix(eqs, variaveis)
    return A, b, variaveis

def imprimir_matriz_b(A, b):
    n = len(A)
    print("Matriz A | Vetor b")
    for i in range(n):
        linha = ' '.join(f"{A[i][j]:10.4f}" for j in range(n))
        print(f"[ {linha} ] | {b[i]:10.4f}")
    print()

def eliminacao_gauss_com_passos(A, b):
    n = A.shape[0]
    A = [[float(A[i, j]) for j in range(n)] for i in range(n)]
    b = [float(b[i, 0]) for i in range(n)]

    print("Sistema inicial:")
    imprimir_matriz_b(A, b)

    # Eliminação para triangularização
    for k in range(n):
        if abs(A[k][k]) < 1e-12:
            raise ZeroDivisionError("Pivô zero detectado, pivotação necessária.")
        for i in range(k + 1, n):
            fator = A[i][k] / A[k][k]
            print(f"Multiplicando linha {k} por {fator:.4f} e subtraindo da linha {i}")
            for j in range(k, n):
                A[i][j] -= fator * A[k][j]
            b[i] -= fator * b[k]
            imprimir_matriz_b(A, b)

    # Retro-substituição
    x = [0] * n
    for i in range(n - 1, -1, -1):
        soma = sum(A[i][j] * x[j] for j in range(i + 1, n))
        x[i] = (b[i] - soma) / A[i][i]

    return x, A, b

def calcular_residuo(A, x, b):
    n = len(A)
    residuo = [0] * n
    for i in range(n):
        soma = 0
        for j in range(n):
            soma += A[i][j] * x[j]
        val = soma - b[i]
        residuo[i] = 0 if abs(val) < 1e-5 else val
    return residuo

# Sistema
equacoes = [
    '1*x1 - 3*x2 + 2*x3 = 11',
    '-2*x1 + 8*x2 - 3*x3 = -15',
    '4*x1 - 6*x2 + 5*x3 = 29'
]

A, b, vars = montar_sistema(equacoes)
solucao, A_triangular, b_modificado = eliminacao_gauss_com_passos(A, b)

print("Solução do sistema:")
for var, val in zip(vars, solucao):
    print(f"{var} = {val:.4f}")

residuo = calcular_residuo(A_triangular, solucao, b_modificado)
print("\nResíduo (Ax - b):")
for i, r in enumerate(residuo):
    print(f"r{i+1} = {r:.4e}" if r != 0 else f"r{i+1} = 0")


Sistema inicial:
Matriz A | Vetor b
[     1.0000    -3.0000     2.0000 ] |    11.0000
[    -2.0000     8.0000    -3.0000 ] |   -15.0000
[     4.0000    -6.0000     5.0000 ] |    29.0000

Multiplicando linha 0 por -2.0000 e subtraindo da linha 1
Matriz A | Vetor b
[     1.0000    -3.0000     2.0000 ] |    11.0000
[     0.0000     2.0000     1.0000 ] |     7.0000
[     4.0000    -6.0000     5.0000 ] |    29.0000

Multiplicando linha 0 por 4.0000 e subtraindo da linha 2
Matriz A | Vetor b
[     1.0000    -3.0000     2.0000 ] |    11.0000
[     0.0000     2.0000     1.0000 ] |     7.0000
[     0.0000     6.0000    -3.0000 ] |   -15.0000

Multiplicando linha 1 por 3.0000 e subtraindo da linha 2
Matriz A | Vetor b
[     1.0000    -3.0000     2.0000 ] |    11.0000
[     0.0000     2.0000     1.0000 ] |     7.0000
[     0.0000     0.0000    -6.0000 ] |   -36.0000

Solução do sistema:
x1 = 0.5000
x2 = 0.5000
x3 = 6.0000

Resíduo (Ax - b):
r1 = 0
r2 = 0
r3 = 0


In [21]:
from sympy import symbols, Eq, linear_eq_to_matrix

def montar_sistema(equacoes):
    n = len(equacoes)
    variaveis = symbols(f'x1:{n+1}')
    eqs = []
    for eq in equacoes:
        lhs, rhs = eq.split('=')
        eqs.append(Eq(eval(lhs, dict(zip([str(v) for v in variaveis], variaveis))), eval(rhs)))
    A, b = linear_eq_to_matrix(eqs, variaveis)
    return A, b, variaveis

def imprimir_matriz_b(A, b):
    n = len(A)
    print("Matriz A | Vetor b")
    for i in range(n):
        linha = ' '.join(f"{A[i][j]:10.4f}" for j in range(n))
        print(f"[ {linha} ] | {b[i]:10.4f}")
    print()

def eliminacao_gauss_pivoteamento(A, b):
    n = A.shape[0]
    A = [[float(A[i, j]) for j in range(n)] for i in range(n)]
    b = [float(b[i, 0]) for i in range(n)]

    print("Sistema inicial:")
    imprimir_matriz_b(A, b)

    for k in range(n):
        # Pivoteamento parcial
        pivo_linha = max(range(k, n), key=lambda i: abs(A[i][k]))
        if abs(A[pivo_linha][k]) < 1e-12:
            raise ZeroDivisionError("Pivô zero detectado, sistema singular ou pivoteamento insuficiente.")
        if pivo_linha != k:
            print(f"Trocando linha {k} com linha {pivo_linha} por pivoteamento")
            A[k], A[pivo_linha] = A[pivo_linha], A[k]
            b[k], b[pivo_linha] = b[pivo_linha], b[k]
            imprimir_matriz_b(A, b)

        for i in range(k + 1, n):
            fator = A[i][k] / A[k][k]
            print(f"Multiplicando linha {k} por {fator:.4f} e subtraindo da linha {i}")
            for j in range(k, n):
                A[i][j] -= fator * A[k][j]
            b[i] -= fator * b[k]
            imprimir_matriz_b(A, b)

    # Retro-substituição
    x = [0] * n
    for i in range(n - 1, -1, -1):
        soma = sum(A[i][j] * x[j] for j in range(i + 1, n))
        x[i] = (b[i] - soma) / A[i][i]

    return x, A, b

def calcular_residuo(A, x, b):
    n = len(A)
    residuo = [0] * n
    for i in range(n):
        soma = 0
        for j in range(n):
            soma += A[i][j] * x[j]
        val = soma - b[i]
        residuo[i] = 0 if abs(val) < 1e-5 else val
    return residuo

# Sistema de exemplo
equacoes = [
    '1*x1 - 3*x2 + 2*x3 = 11',
    '-2*x1 + 8*x2 - 3*x3 = -15',
    '4*x1 - 6*x2 + 5*x3 = 29'
]

A, b, vars = montar_sistema(equacoes)
solucao, A_triangular, b_modificado = eliminacao_gauss_pivoteamento(A, b)

print("Solução do sistema:")
for var, val in zip(vars, solucao):
    print(f"{var} = {val:.4f}")

residuo = calcular_residuo(A_triangular, solucao, b_modificado)
print("\nResíduo (Ax - b):")
for i, r in enumerate(residuo):
    print(f"r{i+1} = {r:.4e}" if r != 0 else f"r{i+1} = 0")


Sistema inicial:
Matriz A | Vetor b
[     1.0000    -3.0000     2.0000 ] |    11.0000
[    -2.0000     8.0000    -3.0000 ] |   -15.0000
[     4.0000    -6.0000     5.0000 ] |    29.0000

Trocando linha 0 com linha 2 por pivoteamento
Matriz A | Vetor b
[     4.0000    -6.0000     5.0000 ] |    29.0000
[    -2.0000     8.0000    -3.0000 ] |   -15.0000
[     1.0000    -3.0000     2.0000 ] |    11.0000

Multiplicando linha 0 por -0.5000 e subtraindo da linha 1
Matriz A | Vetor b
[     4.0000    -6.0000     5.0000 ] |    29.0000
[     0.0000     5.0000    -0.5000 ] |    -0.5000
[     1.0000    -3.0000     2.0000 ] |    11.0000

Multiplicando linha 0 por 0.2500 e subtraindo da linha 2
Matriz A | Vetor b
[     4.0000    -6.0000     5.0000 ] |    29.0000
[     0.0000     5.0000    -0.5000 ] |    -0.5000
[     0.0000    -1.5000     0.7500 ] |     3.7500

Multiplicando linha 1 por -0.3000 e subtraindo da linha 2
Matriz A | Vetor b
[     4.0000    -6.0000     5.0000 ] |    29.0000
[     0.0000   

In [3]:
import numpy as np
from sympy import symbols, Eq, linear_eq_to_matrix

def montar_sistema(equacoes):
    n = len(equacoes)
    variaveis = symbols(f'x1:{n+1}')
    eqs = []
    for eq in equacoes:
        lhs, rhs = eq.split('=')
        eqs.append(Eq(eval(lhs, dict(zip([str(v) for v in variaveis], variaveis))), eval(rhs)))
    A, b = linear_eq_to_matrix(eqs, variaveis)
    A = np.array(A).astype(float)
    b = np.array(b).astype(float).flatten()
    return A, b, variaveis

def lu_sem_pivot(A):
    n = len(A)
    U = A.astype(float).copy()
    L = np.eye(n)
    print('\nInício da decomposição LU sem pivotação:')
    for k in range(n-1):
        print(f'Etapa {k}:')
        for i in range(k+1, n):
            m = U[i,k]/U[k,k]
            print(f"m_{{{i+1},{k+1}}} = {U[i,k]:.4f} / {U[k,k]:.4f} = {m:.4f}")
            L[i,k] = m
            U[i,:] -= m * U[k,:]
            print(f"Linha {i+1}: ({m:.4f})*L_{k+1} + L_{i+1}")
            print('U =\n', U)
            print('L =\n', L)
    return L, U

def lu_com_pivot(A, b):
    n = len(A)
    U = A.astype(float).copy()
    L = np.eye(n)
    P = np.eye(n)
    b_perm = b.copy()
    print('\nInício da decomposição LU COM pivotação parcial:')
    for k in range(n-1):
        print(f'Etapa {k}:')
        maxrow = np.argmax(np.abs(U[k:,k])) + k
        if maxrow != k:
            print(f"Trocando linha {k+1} com {maxrow+1} por pivoteamento parcial.")
            U[[k,maxrow],:] = U[[maxrow,k],:]
            L[[k,maxrow],:k] = L[[maxrow,k],:k]
            P[[k,maxrow],:] = P[[maxrow,k],:]
            b_perm[[k,maxrow]] = b_perm[[maxrow,k]]
        for i in range(k+1, n):
            m = U[i,k]/U[k,k]
            print(f"m_{{{i+1},{k+1}}} = {U[i,k]:.4f} / {U[k,k]:.4f} = {m:.4f}")
            L[i,k] = m
            U[i,:] -= m * U[k,:]
            print(f"Linha {i+1}: ({m:.4f})*L_{k+1} + L_{i+1}")
            print('U =\n', U)
            print('L =\n', L)
    return P, L, U, b_perm

def triangular_solve(U, y):
    n = len(U)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i,i+1:], x[i+1:]))/U[i,i]
    return x

def forward_solve(L, b):
    n = len(L)
    y = np.zeros(n)
    for i in range(n):
        y[i] = (b[i] - np.dot(L[i,:i], y[:i]))/L[i,i]
    return y

def residuos(A, x, b):
    r = b - A @ x
    r[np.abs(r)<1e-3] = 0
    return r

# Usuário DEFINE o sistema abaixo:
equacoes = [
    '1*x1 - 3*x2 + 2*x3 = 11',
    '-2*x1 + 8*x2 - 1*x3 = -15',
    '4*x1 - 6*x2 + 5*x3 = 29'
]

A, b, vars = montar_sistema(equacoes)
print('\n==== LU sem pivotação ===')
L, U = lu_sem_pivot(A)
y = forward_solve(L, b)
x = triangular_solve(U, y)
print('\nSolução (sem pivotação):')
for v, val in zip(vars, x):
    print(f"{v} = {val:.4f}")
print('Resíduo:', residuos(A, x, b))

print('\n==== LU COM pivotação ===')
P, Lp, Up, bp = lu_com_pivot(A, b)
yp = forward_solve(Lp, bp)
xp = triangular_solve(Up, yp)
print('\nSolução (com pivotação):')
for v, val in zip(vars, xp):
    print(f"{v} = {val:.4f}")
print('Resíduo:', residuos(A, xp, b))



==== LU sem pivotação ===

Início da decomposição LU sem pivotação:
Etapa 0:
m_{2,1} = -2.0000 / 1.0000 = -2.0000
Linha 2: (-2.0000)*L_1 + L_2
U =
 [[ 1. -3.  2.]
 [ 0.  2.  3.]
 [ 4. -6.  5.]]
L =
 [[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 0.  0.  1.]]
m_{3,1} = 4.0000 / 1.0000 = 4.0000
Linha 3: (4.0000)*L_1 + L_3
U =
 [[ 1. -3.  2.]
 [ 0.  2.  3.]
 [ 0.  6. -3.]]
L =
 [[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 4.  0.  1.]]
Etapa 1:
m_{3,2} = 6.0000 / 2.0000 = 3.0000
Linha 3: (3.0000)*L_2 + L_3
U =
 [[  1.  -3.   2.]
 [  0.   2.   3.]
 [  0.   0. -12.]]
L =
 [[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 4.  3.  1.]]

Solução (sem pivotação):
x1 = 2.0000
x2 = -1.0000
x3 = 3.0000
Resíduo: [0. 0. 0.]

==== LU COM pivotação ===

Início da decomposição LU COM pivotação parcial:
Etapa 0:
Trocando linha 1 com 3 por pivoteamento parcial.
m_{2,1} = -2.0000 / 4.0000 = -0.5000
Linha 2: (-0.5000)*L_1 + L_2
U =
 [[ 4.  -6.   5. ]
 [ 0.   5.   1.5]
 [ 1.  -3.   2. ]]
L =
 [[ 1.   0.   0. ]
 [-0.5  1.   0. ]
 [ 0.   0.   1. ]]
m_